-- remove any foreign key constraints
ALTER TABLE IF EXISTS category
DROP column id;

-- drop table if exists
DROP TABLE IF EXISTS category;

-- create table
CREATE TABLE category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT,
    category_name TEXT NOT NULL
)
