-- drop tables if exists scripts
DROP TABLE IF EXISTS scripts;

-- create scripts table 
CREATE TABLE scripts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT,
    scripts_name TEXT NOT NULL,
    people TEXT NOT NULL,
    time_spend TEXT NOT NULL, 
    scripts_price TEXT NOT NULL,
    scripts_type TEXT NOT NULL, 
    content TEXT NOT NULL
)