-- create scripts table 
CREATE TABLE if not exists scripts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scripts_name TEXT NOT NULL,
    people TEXT NOT NULL,
    time_spend TEXT NOT NULL, 
    scripts_price TEXT NOT NULL,
    scripts_type TEXT NOT NULL, 
    scripts_image TEXT,
    content TEXT NOT NULL,
    category_id INTEGER REFERENCES category(id),
    admin_id INTEGER REFERENCES admin(id)
);